- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  # IMPORTING VARIABLES
    - name: Import VPC variables
      include_vars: /vars/vpc_setup

      # SET UP VPC
    - name: Create VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{VpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostname: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

  # DISPLAYING THE OUTPUT
    - debug:
        var: vpcout

  # CREATING 3 PUBLIC AND 3 PRIVATE SUBNETS IN 3 DIFFERENT ZONES
    - name: create Public Subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PubSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: MY-pubsub1
      register: pubsub1_out

    - name: create Public Subnet 2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PubSub2Cidr}}"
        map_public: yes
        resource_tags:
          Name: MY-pubsub2
      register: pubsub2_out

    - name: create Public Subnet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PubSub3Cidr}}"
        map_public: yes
        resource_tags:
          Name: MY-pubsub3
      register: pubsub3_out

    - name: create Private Subnet 1 in zone1
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone1}}"
        state: "{{state}}"
        cidr: "{{PrivSub1Cidr}}"
        map_public: yes
        resource_tags:
          Name: MY-Privsub1
      register: Privsub1_out

    - name: create Private Subnet 2 in zone2
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone2}}"
        state: "{{state}}"
        cidr: "{{PrivSub2Cidr}}"
        map_public: yes
        resource_tags:
          Name: MY-Privsub2
      register: Privsub2_out

    - name: create Private Subnet 3 in zone3
      ec2_vpc_subnet:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        az: "{{zone3}}"
        state: "{{state}}"
        cidr: "{{PrivSub3Cidr}}"
        map_public: yes
        resource_tags:
          Name: MY-Privsub3
      register: Privsub3_out

  # SET UP INTERNET GATEWAY AND PUBLIC ROUTE TABLE
    - name: Internet gateway setup
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: "{{state}}"
        resource_tags:
          Name: MY-IGW
      register: IGW_out

    - name: setup public subnet route tables
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: MY-PubRT
        subnets:
          - "{{pubsub1_out.subnet.id}}"
          - "{{pubsub2_out.subnet.id}}"
          - "{{pubsub3_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{IGW_out.gateway_id}}"
      register: PubRT_out

  # SET UP NAT GATEWAY AND ALLOCATE NEW EIP, IF NOT EXISTS. ALSO, SET UP PRIVATE ROUTE TABLE
    - name: NAT gateway setup
      ec2_vpc_nat_gateway:
        state: "{{state}}"
        subnet_id: "{{pubsub1_out.subnet.id}}"    # Creating only one NATGW for practice, or list all 3
        wait: yes
        if_exist_do_not_create: true
        resource_tags:
          Name: MY-NATGW
      register: NATGW_out

    - name: setup public subnet route tables
      ec2_vpc_route_table:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        tags:
          Name: MY-PrivRT
        subnets:
          - "{{privsub1_out.subnet.id}}"
          - "{{privsub2_out.subnet.id}}"
          - "{{privsub3_out.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{NATGW_out.gateway_id}}"
      register: PrivRT_out

    # PRINT AND STORE VARIABLES AND ID'S
    - debug:
        var: "{{item}}"
      loop:
        - vpcout.vpc.id
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.id
        - privsub1_out.subnet.id
        - privsub2_out.subnet.id
        - privsub3_out.subnet.id
        - IGW_out.gateway_id
        - PubRT_out.route_table.id
        - NATGW_out.nat_gateway_id
        - PrivRT_out.route_table.id

    - name: Create variable files for vpc output
      copy:
        content: "vpcid:{{vpcout.vpc.id}}\npubsub1id:{{pubsub1_out.subnet.id}}\npubsub2id:{{pubsub2_out.subnet.id}}\npubsub3id:{{pubsub3_out.subnet.id}}\nprivsub1id:{{privsub1_out.subnet.id}}\nprivsub2id:{{privsub2_out.subnet.id}}\nprivsub3id:{{privsub3_out.subnet.id}}\nIGWid:{{IGW_out.gateway_id}}\npubRTid:{{PubRT_out.route_table.id}}\nNATGWid:{{NATGW_out.nat_gateway_id}}\nprivRTid:{{PrivRT_out.route_table.id}}\n"
        dest: vars/output_vars

